### ISSUE TITLE
2回目に入ったときにエラー

### ISSUE THREAD

**Issue by nennneko5787** [HomuraMC/Homura#6]
このバグは再入室することで起こすことができます！！
このバグの原因はすでにわかっているので明日修正します

**Comment by nennneko5787** [comment]
誰か再現できる人いませんか？

**Comment by sonyakun** [comment]
明日やってみる

**Comment by nennneko5787** [comment]
まだ修正できてません。
原因の特定が遅れてます。

**Comment by sonyakun** [comment]
```
[16:12:30][ERROR] <class 'quarry.types.nbt.TagRoot'>
Traceback (most recent call last):
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/quarry/net/ticker.py", line 122, in fn
    callback()
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/classes/protocol.py", line 127, in send_next_from_queue
    self.send_chunk(x, z, full, heightmap, sections, biomes, block_entities)
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/classes/protocol.py", line 149, in send_chunk
    b"".join(self.buff_type.pack_nbt(entity) for entity in block_entities))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/classes/protocol.py", line 149, in <genexpr>
    b"".join(self.buff_type.pack_nbt(entity) for entity in block_entities))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/quarry/types/buffer/v1_7.py", line 439, in pack_nbt
    return tag.to_bytes()
           ^^^^^^^^^^^^^^
  File "/mnt/c/Users/hm74c/OneDrive/デスクトップ/Homura/quarry/types/nbt.py", line 190, in to_bytes
    string += Buffer.pack("b", _ids[type(tag)])
                               ~~~~^^^^^^^^^^^
KeyError: <class 'quarry.types.nbt.TagRoot'>
```

**Comment by AmaseCocoa** [comment]
これはQuarry辞めるから解決かな...？

**Comment by sonyakun** [comment]
これはQuarry辞めるから解決かな

**Comment by nennneko5787** [comment]
そうだね
